services:
  minio:
    image: bitnami/minio:2024
    container_name: minio
    restart: always
    ports:
      - 9000:9000 # S3 API
      - 9001:9001 # MinIO Console
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=foobar
    volumes:
      - minio_storage:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
  mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio http://minio:9000 minio-root-user minio-root-password; do
        echo 'Waiting for MinIO to be ready...'
        sleep 5
      done;
      mc anonymous set download myminio/foobar;
      exit 0;
      "
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hello_django_dev
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  minio_storage:
  postgres_data:
  redis_data:
