# Common service configuration for web and worker
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  develop:
    watch:
      - path: .
        action: sync
        target: /app
  environment:
    DATABASE_URL: postgres://hello_django:hello_django@db:5432/hello_django_dev
    TWO_CAPTCHA_API_KEY: 373ae125ef517c4657d81a2d22022654
    REDIS_URL: redis://redis:6379/0
    DEBUG: "True"
    SECRET_KEY: backend
    CORS_ALLOWED_ORIGINS: http://localhost:8110,http://localhost:8888
    CSRF_TRUSTED_ORIGINS: http://localhost:8110,http://localhost:8888
    R2_BUCKET_NAME: backend
    R2_DOMAIN_NAME: 127.0.0.1:9000/backend
    R2_ENDPOINT_URL: http://minio:9000
    R2_URL_PROTOCOL: "http:"
    R2_KEY: minio-root-user
    R2_SECRET: minio-root-password
    PYTHONTRACEMALLOC: 1
    PYTHONUNBUFFERED: 1

services:
  web:
    <<: *base
    ports:
      - 8110:8888
    healthcheck:
      test: curl --fail http://localhost:8888/ || exit 1
      interval: 10s
      retries: 10
      timeout: 2s
    command: ["bash", "-c", "cd backend && ./start.sh"]
    depends_on:
      - minio
      - db
      - redis
      - worker
  worker:
    <<: *base
    command:
      ["bash", "-c", "cd backend && uv run manage.py scheduler_worker default"]
    # We should not depend on ourself
    depends_on:
      - db
      - redis
      - minio
